### ISSUE TITLE
Is there an up to date changelog or release doc?

### ISSUE THREAD

**Issue by KarneAsada** [LottieFiles/lottie-player#123]
I noticed that the changelog and release tags stopped being updated with v1.2.1 (1.4.1 on npm?). Is there a doc that lists what changes each release has? It's very useful when determining whether to update to the latest package.

**Comment by karamalie** [comment]
hi @KarneAsada , just noticed that the release tags wernt being updated. We ve been using semantic release to push updates and now are in the process of changing it to changesets. the npm version is where the latest updates are always pushed to. but we re trying to publish to npm and github registries both and working on making it so that both versions are the same on both sides. 

Would it be useful for you if we maintained a separate readme doc on the github repo to log changes? We already have an internal log we keep and could add it to the repo as a separate file

**Comment by samuelOsborne** [comment]
Hi @KarneAsada, the changelog has been updated: https://github.com/LottieFiles/lottie-player/blob/master/CHANGELOG.md

**Comment by dferretti** [comment]
Hey @karamalie , speaking for myself it would be helpful if the github releases were the same version as the npm versions. I use the github feature to Watch this repo and others for releases: 
![image](https://user-images.githubusercontent.com/24608502/154090616-f04cf70e-39fc-492a-b5cf-06ce82f90902.png)
